name: RestartAR
version: '1.8.0'
main: me.marioneto4ka.restartar.RestartAR
api-version: '1.21'
commands:
  autorestart:
    usage: /autorestart [time]
    permission: restartar.restart
  ar:
    usage: /ar <cancel|reload>
    permission: restartar.admin
permissions:
  restartar.restart:
    default: op
  restartar.admin:
    default: op
